### ISSUE TITLE
Request: Updated version

### ISSUE THREAD

**Issue by mwkcoding** [coreymcmahon/laravel-aws-audio-stream#2]
Would you be willing to make an updated version of this for current Laravel version and new AWS SDK? Or should it still mostly work the same way?

**Comment by coreymcmahon** [comment]
Hi Mikkel,

It uses S3 + Cloudfront APIs which haven't changed much and are generally backwards compatible, so I assume it should work without significant changes.

The useful code is located here:

https://github.com/coreymcmahon/laravel-aws-audio-stream/blob/master/app/controllers/StreamsController.php

* Stores MP3s on S3 (see `store()`)
* Renders the main view (see `playStream()`)

... and here:

https://github.com/coreymcmahon/laravel-aws-audio-stream/blob/master/app/views/streams/play.blade.php

* Frontend for opening and playing the stream.
* Requires you import `jwplayer.js`.

Best of luck!
